Update tag-check

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -52,8 +52,15 @@ jobs:
       - name: Extract Version
         id: get_version
         run: |
-          VERSION=$(python -c "import frazer; print(frazer.__version__)")
+          VERSION=$(grep -oP "(?<=__version__ = \"))[^\"]+" frazer/__init__.py)
+          echo "Version found: $VERSION"
+          SEMVER_REGEX="^([0-9]+)\.([0-9]+)\.([0-9]+)(-[0-9A-Za-z-.]+)?(\+[0-9A-Za-z-.]+)?$"
+          if [[ ! "$VERSION" =~ $SEMVER_REGEX ]]; then
+            echo "❌ Invalid semantic version: $VERSION"
+            exit 1
+          fi
           echo "VERSION=$VERSION" >> $GITHUB_ENV
+          echo "✅ Valid semantic version: $VERSION"
 
       - name: Create Git Tag
         run: |
