Fix deploy to AWS Lambda (#13)
- Fix deploy to AWS to avoid leaking secrets. (Closes #12)
- Reestructure webapp folder structure.
- Update deploy to check if tag exists before proceeding.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -3,16 +3,18 @@ name: Deploy
 on:
   push:
     branches:
-        - main
+      - main
 
 permissions:
   contents: write
 
+env:
+  LAMBDA_FUNCTION: frazer
+
 jobs:
   deploy:
-    name: Deploy to AWS Lambda
+    name: Deploy app
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
@@ -22,41 +24,71 @@ jobs:
         with:
           python-version: '3.12'
 
-      - name: Create Lambda package
-        run: |
-          python -m pip install --upgrade pip
-          make lambda
-
-      - name: Install AWS CLI
-        run: |
-          pip install awscli
-
-      - name: Configure AWS CLI
-        run: |
-          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws configure set region ${{ secrets.AWS_REGION }}
-
-      - name: Deploy to Lambda
-        run: |
-          aws lambda update-function-code --function-name frazer --zip-file fileb://frazer-lambda.zip
-
-      - name: Build frontend
-        env: 
-          SENTENCE_API_URL: ${{ secrets.SENTENCE_API_URL }}
+      - name: Build frazer
         run: |
           pip install -e .
-          make build-site
-
-      - name: Deploy site
-        run: |
-          aws s3 cp site/frazer.html s3://${{ secrets.BUCKET }}/frazer.html --acl public-read
 
       - name: Extract Version
         id: get_version
         run: |
           VERSION=$(python -c "import frazer; print(frazer.__version__)")
           echo "VERSION=$VERSION" >> $GITHUB_ENV
+
+      - name: Check version exists
+        run: |
+          git fetch --tags
+          TAGS=$(git tag)
+          if echo "$TAGS" | grep -q "^v$VERSION$"; then
+            echo "Tag v$VERSION exists! Bump the __version__ of the app to proceed with the deploy."
+            exit 1
+          fi
+
+      - name: Create Lambda package
+        run: |
+          python -m pip install --upgrade pip
+          mkdir package
+          pip install -r requirements.txt --target=package/ --platform=manylinux2014_aarch64 --implementation=cp --only-binary=:all:
+          cp -r frazer package/
+          cp frazer/lambda.py logging.conf package/
+          cd package/ ; zip -r ../frazer-lambda.zip . -x "*__pycache__*"
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region:  ${{ secrets.AWS_REGION }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
+      - name: Deploy to AWS Lambda
+        run: |
+          aws lambda update-function-code \
+            --function-name $LAMBDA_FUNCTION \
+            --zip-file fileb://frazer-lambda.zip \
+            --no-cli-pager \
+            --query 'FunctionArn' --output text
+      
+          echo "Waiting for Lambda update to complete..."
+          aws lambda wait function-updated --function-name $LAMBDA_FUNCTION
+      
+          # Get the update-function-code status
+          STATUS=$(aws lambda get-function --function-name $LAMBDA_FUNCTION --query 'Configuration.LastUpdateStatus' --output text)
+      
+          if [[ "$STATUS" == "Successful" ]]; then
+            echo "✅ Deployment successful!"
+          else
+            echo "❌ Deployment failed with status: $STATUS"
+            exit 1
+          fi
+
+      - name: Build webapp
+        env: 
+          SENTENCE_API_URL: ${{ secrets.SENTENCE_API_URL }}
+        run: |
+          make build-site
+
+      - name: Deploy site
+        run: |
+          aws s3 cp site/frazer.html s3://${{ secrets.BUCKET }}/frazer.html --acl public-read
 
       - name: Create Git Tag
         run: |
