Update tag-check

diff --git a/.github/workflows/tag-check.yml b/.github/workflows/tag-check.yml
--- a/.github/workflows/tag-check.yml
+++ b/.github/workflows/tag-check.yml
@@ -21,10 +21,15 @@ jobs:
       - name: Extract version from Python file
         id: get_version
         run: |
-          pip install -e .
-          VERSION=$(python -c "import frazer; print(frazer.__version__)")
+          VERSION=$(grep -oP "(?<=__version__ = \"))[^\"]+" frazer/__init__.py)
           echo "Version found: $VERSION"
+          SEMVER_REGEX="^([0-9]+)\.([0-9]+)\.([0-9]+)(-[0-9A-Za-z-.]+)?(\+[0-9A-Za-z-.]+)?$"
+          if [[ ! "$VERSION" =~ $SEMVER_REGEX ]]; then
+            echo "❌ Invalid semantic version: $VERSION"
+            exit 1
+          fi
           echo "VERSION=$VERSION" >> $GITHUB_ENV
+          echo "✅ Valid semantic version: $VERSION"
 
       - name: Check if Git tag exists
         run: |
